# Approche par fenêtres glissantes {-}

Dans l'approche par fenêtre glissante, une fenêtre de longueur spécifiée se déplace sur les données, en se décalant d'un pas défini. A chaque glissement le nombre de données contenu dans la fenêtre est calculé. La fonction _Fenetres_glissantes.R_ permet de faire ce calcul (Chunk \@ref(exr:chunk11)), à partir d'une table contenant au minimum les colonnes _chr_ et _pos_, en sortie, le nombre de valeurs contenues dans chaque fenêtre est reporté dans une colonne _nValues_ et la position de chaque fenêtre est définie par les colonnes _Start_ et _End_. Ce type de représentation permet de visualiser les régions génomiques qui sont concentrées en SNP sélectionnés sur la base d'une statistique d'intérêt. Cette approche est particulièrement intéressante quand les signatures de sélections sont faibles.

```{exercise, chunk11}
<span style="color:darkgreen">Visualisation par fenêtres glissantes.</span>
```
<p style="font-family: calibri; font-size:11pt; font-style:italic; color:darkgreen">
Deux paramètres sont à renseigner: la taille de la fenêtre et le pas de glissement.<br>
Une fois la fonction exécutée le résultat peut être visualisé par un plot (pos, nValues) de chaque chromosome<br>
</p>
```{r plot_slide_BF, class.source='bg-chunk', class.output='bg-output'}
#travail sur le top 1% des XtX.
df<-subset(Full.res, M_XtX > quantile(Full.res$M_XtX, probs=0.99 ))
slide_x <- sliding_window_counts(df, window_size = 50000, step_size = 5000)

#plot de la concentration du top 1% des XtX
Manplot.SX = ggplot(data=slide_x, aes(x=Start, y=nValues)) +
  geom_point(aes(color=chr), alpha=0.8, size=1.5) +
  theme(axis.title.x=element_blank(), axis.text.x=element_blank(), axis.ticks.x=element_blank())
Manplot.SX + ggtitle("Plot du nombre de XtX dans le top 1% par fenêtres de 50Kb")+
  facet_wrap(~chr, scales = 'free_x', strip.position = c("bottom"))

#travail sur les Bayes Factors >= 15
df<-subset(Full.res, BF.dB. >= 15)
slide_bf <- sliding_window_counts(df, window_size = 50000, step_size = 5000)

#plot de la concentration en BF >= 15
Manplot.SBF = ggplot(data=slide_bf, aes(x=Start, y=nValues)) +
  geom_point(aes(color=chr), alpha=0.8, size=1.5) +
  theme(axis.title.x=element_blank(), axis.text.x=element_blank(), axis.ticks.x=element_blank())
Manplot.SBF + ggtitle("Plot du nombre de Bayes Factors >= 15 par fenêtres de 50Kb")+
  facet_wrap(~chr, scales = 'free_x', strip.position = c("bottom"))

#travail sur le top 1% des contrastes
df<-subset(Full.res, M_C2 > quantile(Full.res$M_C2, probs=0.99 ))
slide_C2 <- sliding_window_counts(df, window_size = 50000, step_size = 5000)

#plot de la concentration du top 1% des C2
Manplot.SC2 = ggplot(data=slide_C2, aes(x=Start, y=nValues)) +
  geom_point(aes(color=chr), alpha=0.8, size=1.5) +
  theme(axis.title.x=element_blank(), axis.text.x=element_blank(), axis.ticks.x=element_blank())
Manplot.SC2 + ggtitle("Plot du nombre de contraste C2 dans le top 1% par fenêtres de 50Kb")+
  facet_wrap(~chr, scales = 'free_x', strip.position = c("bottom"))
```