# BayPass 2.3 : présentation.
Le logiciel BayPass est un logiciel de génomique des populations qui vise principalement à l'identification de marqueurs génétiques soumis à la sélection et/ou associés à des covariables spécifiques à la population (variables environnementales, phénotypiques, quantitatives, catégorielles…). Par une approche baysienne il évalue une matrice Ω de covariance des fréquences alléliques des populations résultant de leur histoire démographique.  Deux manières d’estimer ces fréquences alléliques sont disponibles soit en se basant sur les génotypes référence/mutant des individus analysés soit, lorsque l’on active le « pool-seq mode », ces fréquences alléliques sont calculées en regard de la profondeur de séquençage (reads count) et pondérées par le nombre d’individus qui ont contribué à cette profondeur. C’est cette seconde approche que nous considérerons dans cet article. 

BayPass propose 3 modèles statistiques d’analyse :
### Le Core Model, est le modèle de base, il permet de calculer la matrice de covariance Ω et d’attribuer une statistique de différenciation XtX à chaque SNP, et ainsi de scanner le génome pour identifier les régions différenciées sans autres informations.
### Le Standard Model, permet, l’orsque l’on fournit une ou plusieurs covariables (environnementales, phénotypiques…), de calculer en plus une statistique BF (Bayes Factor) pour chaque marqueur génétique et chaque covariable. C’est un modèle tout en un qui intègre le calcul des XtX et de la matrice Ω, il est adapté au faible nombre de population (< 815).
### L’Auxiliairy Model, a une approche différente dans le calcul de la statistique BF, sans entrer dans le détail il est plus adapté au grand nombre de population (> 815)., En contrepartie ce modèle nécessite que l’on fournisse une matrice Ω déjà calculé par une analyse Core Model, il recalcule alors les XtX et la statistique B.

Ces covariables évoquées doivent être distribuées en gradient entre les populations (différence de température, d’altitude…), en complément, dans le cas où la covariable étudiée serait purement binaire (sensible/résistant, gros/petit…), les modèles Standard et Auxiliaire peuvent calculer une statistique C2 qui évalue le contraste de différence des fréquences alléliques entre 2 groupes de populations. 
